# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-20 17:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('gender', models.BooleanField(help_text='Designates whether person is male or female')),
                ('age', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(200)])),
                ('institute_name', models.CharField(max_length=255)),
                ('standard', models.CharField(max_length=128)),
                ('financial_assistance', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=10000)),
                ('profile_pic', models.ImageField(blank=True, default='images/profile_pictures/default.jpg', upload_to='images/profile_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='SocialActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=10000)),
                ('financial_assistance', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/social_activities/')),
            ],
        ),
    ]
